// GENERATED by model_emit.py from ConvertWord.call_js - DO NOT EDIT
// (verbatim converter functions: norm / skel / translit)
// --- NORMALIZE: collapse spelling variants to canonical ---
// Must stay in sync with norm() in build_dict.py and searchTermToKey
// in the lexical model.
function norm(s) {
  s = s.toLowerCase();
  // Strip apostrophes and Arabizi digits (2=\u0621, 3=\u0639) — dict keys are bare
  s = s.replace(/['\u201923]/g, '');
  // c → s before e/i/y (cinema→sinema), else c → k; 'ch' protected
  s = s.replace(/c(?=[eiy])/g, 's');
  s = s.replace(/c(?!h)/g, 'k');
  // Word-final consonant+y → i  (kardy → kardi)
  s = s.replace(/([^aeiou])y$/, '$1i');
  // Word-final 'eh' → 'e'  (kardeh → karde)
  s = s.replace(/eh$/, 'e');
  // Consonant equivalences
  s = s.replace(/x/g, 'kh');
  s = s.replace(/q/g, 'gh');
  s = s.replace(/w/g, 'v');
  s = s.replace(/ph/g, 'f');
  // Long vowels → short
  s = s.replace(/aa/g, 'a');
  s = s.replace(/oo/g, 'o');
  s = s.replace(/ee/g, 'i');
  s = s.replace(/ou/g, 'o');
  // u/oo equivalence
  s = s.replace(/u/g, 'o');
  // ei/ey → i
  s = s.replace(/ey/g, 'i');
  s = s.replace(/ei/g, 'i');
  // y → i everywhere (saye→saie, miyam→miiam→miam)
  s = s.replace(/y/g, 'i');
  // Collapse doubled letters
  s = s.replace(/(.)\1+/g, '$1');
  return s;
}

// --- SKELETON: vowel-stripped key for tier-3 lookup ---
// Must stay in sync with skeleton() in build_dict.py.
function skel(s) {
  if (s.length < 2) { return s; }
  var head = s[0];
  if ('aeou'.indexOf(head) >= 0) { head = 'a'; }
  var body = s.slice(1);
  if (body.length > 1) {
    body = body.slice(0, -1).replace(/[aeo]/g, '') + body.slice(-1);
  }
  return head + body;
}

// --- ALGORITHMIC TRANSLITERATION: for unknown words ---
// H8 heuristic (eval_translit.mjs, 2026-07-17): last-vowel 'a' written,
// 'a' before n+vowel/end written (-an/-ani patterns), surname suffix
// table, all other medial short 'a' unwritten. Scored 29.5% exact-match
// vs 25.2% for always-alef on 33k human-romanized name/word pairs.
function translit(s) {
  s = s.toLowerCase();
  s = s.replace(/c(?=[eiy])/g, 's');
  s = s.replace(/c(?!h)/g, 'k');
  // Collapse double consonants BEFORE transliterating
  s = s.replace(/([^aeiou])\1+/g, '$1');

  // Surname/word suffix table (checked once, longest-ish first)
  var suffix = '';
  var SUF = [
    ['ian',   '\u06CC\u0627\u0646'],
    ['zadeh', '\u0632\u0627\u062F\u0647'],
    ['zade',  '\u0632\u0627\u062F\u0647'],
    ['pour',  '\u067E\u0648\u0631'],
    ['poor',  '\u067E\u0648\u0631'],
    ['nejad', '\u0646\u0698\u0627\u062F'],
    ['nezhad','\u0646\u0698\u0627\u062F'],
    ['abadi', '\u0622\u0628\u0627\u062F\u06CC'],
    ['vand',  '\u0648\u0646\u062F'],
    ['lou',   '\u0644\u0648'],
    ['loo',   '\u0644\u0648'],
    ['khah',  '\u062E\u0648\u0627\u0647'],
    ['far',   '\u0641\u0631']
  ];
  for (var si = 0; si < SUF.length; si++) {
    var suf = SUF[si][0];
    if (s.length > suf.length + 2 && s.slice(-suf.length) === suf) {
      if (suf === 'ian' && 'aeiou'.indexOf(s[s.length - 4]) >= 0) { continue; }
      s = s.slice(0, -suf.length);
      suffix = SUF[si][1];
      break;
    }
  }

  // Index of the last vowel of the (suffix-stripped) stem
  var lastVowelIdx = -1;
  for (var vi = s.length - 1; vi >= 0; vi--) {
    if ('aeiou'.indexOf(s[vi]) >= 0) { lastVowelIdx = vi; break; }
  }

  var out = '';
  var i = 0;
  var len = s.length;
  var di = {
    'sh':'\u0634','ch':'\u0686','zh':'\u0698','kh':'\u062E',
    'gh':'\u063A','ph':'\u0641'
  };
  var co = {
    'b':'\u0628','p':'\u067E','t':'\u062A','s':'\u0633',
    'j':'\u062C','d':'\u062F','z':'\u0632','r':'\u0631',
    'f':'\u0641','k':'\u06A9','g':'\u06AF','l':'\u0644',
    'm':'\u0645','n':'\u0646','v':'\u0648','w':'\u0648',
    'h':'\u0647','y':'\u06CC','q':'\u0642','x':'\u062E'
  };
  while (i < len) {
    if (i + 1 < len) {
      var pair = s[i] + s[i+1];
      if (di[pair]) { out += di[pair]; i += 2; continue; }
    }
    var c = s[i];
    if (co[c]) { out += co[c]; }
    else if (c === 'a') {
      if (i === 0 && i + 1 < len && s[i+1] === 'a') {
        out += '\u0622'; i += 2; continue;
      }
      if (i + 1 < len && s[i+1] === 'a') {
        out += '\u0627'; i += 2; continue;
      }
      if (i === 0) { out += '\u0627'; }
      else if (i === lastVowelIdx) { out += '\u0627'; }
      else if (s[i+1] === 'n' && (i+2 >= len || 'aeiou'.indexOf(s[i+2]) >= 0)) {
        out += '\u0627';
      }
      // else: unwritten short a
    }
    else if (c === 'o') {
      if (i + 1 < len && s[i+1] === 'o') {
        out += (i === 0) ? '\u0627\u0648' : '\u0648';
        i += 2; continue;
      }
      if (i === 0) { out += '\u0627\u0648'; }
      else if (i === len - 1) { out += '\u0648'; }
    }
    else if (c === 'i') {
      if (i === 0) { out += '\u0627\u06CC'; }
      else { out += '\u06CC'; }
    }
    else if (c === 'e') {
      if (i + 1 < len && s[i+1] === 'e') {
        out += (i === 0) ? '\u0627\u06CC' : '\u06CC';
        i += 2; continue;
      }
      if (i === 0) { out += '\u0627'; }
      else if (i === len - 1) { out += '\u0647'; }
    }
    else if (c === 'u') { out += '\u0648'; }
    else if (c === '2') { out += '\u0621'; }
    else if (c === '3') { out += '\u0639'; }
    else if (c === "'" || c === '\u2019') { out += '\u0639'; }
    i++;
  }
  return (out + suffix) || s;
}

