/*
 * mattin.fa.fingilish.model.ts
 *
 * Keyman Lexical Model — Fingilish (Latin input → Persian output)
 *
 * The wordlist contains Persian words. searchTermToKey converts them to
 * Latin keys for trie indexing, and also normalizes the user's typed Latin
 * before lookup. Both paths must produce the same key for a match.
 *
 * All helpers are defined INSIDE searchTermToKey because kmc compiles the
 * model in a sandboxed scope where top-level module functions are not
 * accessible at runtime.
 *
 * RTL FIX: isRTL is set to true so the suggestion banner renders Persian
 * correctly. Persian words in the wordlist are wrapped with BiDi isolation
 * characters (U+2067 RLI / U+2069 PDI) as a belt-and-suspenders fix for
 * platforms where isRTL alone doesn't drive banner direction.
 * searchTermToKey strips these before processing.
 *
 * Normalization rules (must match norm() in build_dict.py and
 * ConvertWord.call_js):
 *   strip '/2/3, c→s before e/i/y else c→k ('ch' protected),
 *   [consonant]y$→i, eh$→e
 *   x→kh, q→gh, w→v, ph→f
 *   aa→a, oo→o, ee→i, ou→o
 *   u→o  (khub → khob)
 *   ey→i, ei→i  (kheyli → khili), y→i everywhere
 *   collapse doubled letters
 */

const source: LexicalModelSource = {
  format: "trie-1.0",
  wordBreaker: { use: "default" },
  punctuation: { insertAfterWord: " " },
  languageUsesCasing: false,
  isRTL: true,
  sources: ["words/fingilish.wordlist.tsv"],

  searchTermToKey: function(term: string): string {
    // Strip BiDi isolates (wordlist wraps Persian in RLI/PDI)
    term = term.replace(/[\u2066-\u2069]/g, '').replace(/^\s+|\s+$/g, '');

    // ==== GENERATED BY gen_model_key.py — DO NOT EDIT BY HAND ====
    // Tables come from build_dict.py (single source of truth).
    var P2L_MULTI: Record<string, string> = {"\u062e\u0648": "kho"};
    var P2L_SINGLE: Record<string, string> = {"\u0621": "", "\u0622": "a", "\u0626": "", "\u0627": "a", "\u0628": "b", "\u062a": "t", "\u062b": "s", "\u062c": "j", "\u062d": "h", "\u062e": "kh", "\u062f": "d", "\u0630": "z", "\u0631": "r", "\u0632": "z", "\u0633": "s", "\u0634": "sh", "\u0635": "s", "\u0636": "z", "\u0637": "t", "\u0638": "z", "\u0639": "", "\u063a": "gh", "\u0641": "f", "\u0642": "gh", "\u0644": "l", "\u0645": "m", "\u0646": "n", "\u0647": "h", "\u067e": "p", "\u0686": "ch", "\u0698": "zh", "\u06a9": "k", "\u06af": "g", "\u06cc": "i"};
    var P2L_CONS: string = "\u0628\u062a\u062b\u062c\u062d\u062e\u062f\u0630\u0631\u0632\u0633\u0634\u0635\u0636\u0637\u0638\u0639\u063a\u0641\u0642\u0644\u0645\u0646\u0647\u067e\u0686\u06a9\u06af\u06cc";

    function p2l(word: string): string {
      if (!word) { return "?"; }
      var n = word.length;
      var result = "";
      var i = 0;
      while (i < n) {
        var ch = word[i];
        if (i + 1 < n) {
          var pair = word[i] + word[i + 1];
          if (P2L_MULTI.hasOwnProperty(pair)) {
            result += P2L_MULTI[pair];
            i += 2;
            continue;
          }
        }
        if (ch === '\u0648') {
          var prevC = (i > 0 && P2L_CONS.indexOf(word[i - 1]) >= 0);
          var nextC = (i + 1 < n && P2L_CONS.indexOf(word[i + 1]) >= 0);
          var nextEnd = (i + 1 >= n);
          if (i === 0) { result += "va"; }
          else if (i === 1 && word[0] === '\u0627') { result += "oo"; }
          else if (prevC && (nextC || nextEnd)) { result += "oo"; }
          else { result += "v"; }
          i += 1;
          continue;
        }
        if (ch === '\u0647' && i === n - 1) { result += "e"; i += 1; continue; }
        if (ch === '\u0639' && i === 0) { result += "a"; i += 1; continue; }
        if (P2L_SINGLE.hasOwnProperty(ch)) { result += P2L_SINGLE[ch]; }
        i += 1;
      }
      result = result.replace(/(.)\1{2,}/g, '$1$1');
      result = result.replace(/^\s+|\s+$/g, '');
      return result || "?";
    }

    function normL(s: string): string {
      s = s.toLowerCase();
      s = s.replace(/['\u201923]/g, '');
      s = s.replace(/c(?=[eiy])/g, 's');
      s = s.replace(/c(?!h)/g, 'k');
      s = s.replace(/([^aeiou])y$/, '$1i');
      s = s.replace(/eh$/, 'e');
      s = s.replace(/x/g, 'kh');
      s = s.replace(/q/g, 'gh');
      s = s.replace(/w/g, 'v');
      s = s.replace(/ph/g, 'f');
      s = s.replace(/aa/g, 'a');
      s = s.replace(/oo/g, 'o');
      s = s.replace(/ee/g, 'i');
      s = s.replace(/ou/g, 'o');
      s = s.replace(/u/g, 'o');
      s = s.replace(/ey/g, 'i');
      s = s.replace(/ei/g, 'i');
      s = s.replace(/y/g, 'i');
      s = s.replace(/(.)\1+/g, '$1');
      return s;
    }

    function skelL(s: string): string {
      if (s.length < 2) { return s; }
      var head = s[0];
      if ('aeou'.indexOf(head) >= 0) { head = 'a'; }
      var body = s.slice(1);
      if (body.length > 1) {
        body = body.slice(0, -1).replace(/[aeo]/g, '') + body.slice(-1);
      }
      return head + body;
    }
    // ==== END GENERATED ====
    if (/[\u0600-\u06FF]/.test(term)) { term = p2l(term); }
    return skelL(normL(term));
  },
};

export default source;