#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_calljs.py — Assemble ConvertWord.call_js from template + dictionary

Run after build_dict.py:
  python build_dict.py        # generates fingilish_dict.json
  python build_calljs.py      # generates ConvertWord.call_js

Then rebuild with kmc:
  kmc build source/fingilish.kmn --out-file build/fingilish.js
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DICT_JSON = BASE_DIR / "fingilish_dict.json"
OUTPUT = BASE_DIR / "ConvertWord.call_js"

TEMPLATE = r'''// ConvertWord.call_js — Fingilish → Persian conversion engine
// Generated by build_calljs.py — do NOT edit by hand
// API: target.getTextBeforeCaret(), .deleteCharsBeforeCaret(n), .insertTextBeforeCaret(s)

// --- DICTIONARY (%%COUNT%% entries) ---
var D = %%DICT%%;
// --- SKELETON BANK (%%SKELCOUNT%% vowel-stripped entries) ---
var S = %%SKEL%%;

// --- NORMALIZE: collapse spelling variants to canonical ---
// Must stay in sync with norm() in build_dict.py and searchTermToKey
// in the lexical model.
function norm(s) {
  s = s.toLowerCase();
  // Strip apostrophes and Arabizi digits (2=\u0621, 3=\u0639) — dict keys are bare
  s = s.replace(/['\u201923]/g, '');
  // c → s before e/i/y (cinema→sinema), else c → k; 'ch' protected
  s = s.replace(/c(?=[eiy])/g, 's');
  s = s.replace(/c(?!h)/g, 'k');
  // Word-final consonant+y → i  (kardy → kardi)
  s = s.replace(/([^aeiou])y$/, '$1i');
  // Word-final 'eh' → 'e'  (kardeh → karde)
  s = s.replace(/eh$/, 'e');
  // Consonant equivalences
  s = s.replace(/x/g, 'kh');
  s = s.replace(/q/g, 'gh');
  s = s.replace(/w/g, 'v');
  s = s.replace(/ph/g, 'f');
  // Long vowels → short
  s = s.replace(/aa/g, 'a');
  s = s.replace(/oo/g, 'o');
  s = s.replace(/ee/g, 'i');
  s = s.replace(/ou/g, 'o');
  // u/oo equivalence
  s = s.replace(/u/g, 'o');
  // ei/ey → i
  s = s.replace(/ey/g, 'i');
  s = s.replace(/ei/g, 'i');
  // y → i everywhere (saye→saie, miyam→miiam→miam)
  s = s.replace(/y/g, 'i');
  // Collapse doubled letters
  s = s.replace(/(.)\1+/g, '$1');
  return s;
}

// --- SKELETON: vowel-stripped key for tier-3 lookup ---
// Must stay in sync with skeleton() in build_dict.py.
function skel(s) {
  if (s.length < 2) { return s; }
  var head = s[0];
  if ('aeou'.indexOf(head) >= 0) { head = 'a'; }
  var body = s.slice(1);
  if (body.length > 1) {
    body = body.slice(0, -1).replace(/[aeo]/g, '') + body.slice(-1);
  }
  return head + body;
}

// --- ALGORITHMIC TRANSLITERATION: for unknown words ---
// H8 heuristic (eval_translit.mjs, 2026-07-17): last-vowel 'a' written,
// 'a' before n+vowel/end written (-an/-ani patterns), surname suffix
// table, all other medial short 'a' unwritten. Scored 29.5% exact-match
// vs 25.2% for always-alef on 33k human-romanized name/word pairs.
function translit(s) {
  s = s.toLowerCase();
  s = s.replace(/c(?=[eiy])/g, 's');
  s = s.replace(/c(?!h)/g, 'k');
  // Collapse double consonants BEFORE transliterating
  s = s.replace(/([^aeiou])\1+/g, '$1');

  // Surname/word suffix table (checked once, longest-ish first)
  var suffix = '';
  var SUF = [
    ['ian',   '\u06CC\u0627\u0646'],
    ['zadeh', '\u0632\u0627\u062F\u0647'],
    ['zade',  '\u0632\u0627\u062F\u0647'],
    ['pour',  '\u067E\u0648\u0631'],
    ['poor',  '\u067E\u0648\u0631'],
    ['nejad', '\u0646\u0698\u0627\u062F'],
    ['nezhad','\u0646\u0698\u0627\u062F'],
    ['abadi', '\u0622\u0628\u0627\u062F\u06CC'],
    ['vand',  '\u0648\u0646\u062F'],
    ['lou',   '\u0644\u0648'],
    ['loo',   '\u0644\u0648'],
    ['khah',  '\u062E\u0648\u0627\u0647'],
    ['far',   '\u0641\u0631']
  ];
  for (var si = 0; si < SUF.length; si++) {
    var suf = SUF[si][0];
    if (s.length > suf.length + 2 && s.slice(-suf.length) === suf) {
      if (suf === 'ian' && 'aeiou'.indexOf(s[s.length - 4]) >= 0) { continue; }
      s = s.slice(0, -suf.length);
      suffix = SUF[si][1];
      break;
    }
  }

  // Index of the last vowel of the (suffix-stripped) stem
  var lastVowelIdx = -1;
  for (var vi = s.length - 1; vi >= 0; vi--) {
    if ('aeiou'.indexOf(s[vi]) >= 0) { lastVowelIdx = vi; break; }
  }

  var out = '';
  var i = 0;
  var len = s.length;
  var di = {
    'sh':'\u0634','ch':'\u0686','zh':'\u0698','kh':'\u062E',
    'gh':'\u063A','ph':'\u0641'
  };
  var co = {
    'b':'\u0628','p':'\u067E','t':'\u062A','s':'\u0633',
    'j':'\u062C','d':'\u062F','z':'\u0632','r':'\u0631',
    'f':'\u0641','k':'\u06A9','g':'\u06AF','l':'\u0644',
    'm':'\u0645','n':'\u0646','v':'\u0648','w':'\u0648',
    'h':'\u0647','y':'\u06CC','q':'\u0642','x':'\u062E'
  };
  while (i < len) {
    if (i + 1 < len) {
      var pair = s[i] + s[i+1];
      if (di[pair]) { out += di[pair]; i += 2; continue; }
    }
    var c = s[i];
    if (co[c]) { out += co[c]; }
    else if (c === 'a') {
      if (i === 0 && i + 1 < len && s[i+1] === 'a') {
        out += '\u0622'; i += 2; continue;
      }
      if (i + 1 < len && s[i+1] === 'a') {
        out += '\u0627'; i += 2; continue;
      }
      if (i === 0) { out += '\u0627'; }
      else if (i === lastVowelIdx) { out += '\u0627'; }
      else if (s[i+1] === 'n' && (i+2 >= len || 'aeiou'.indexOf(s[i+2]) >= 0)) {
        out += '\u0627';
      }
      // else: unwritten short a
    }
    else if (c === 'o') {
      if (i + 1 < len && s[i+1] === 'o') {
        out += (i === 0) ? '\u0627\u0648' : '\u0648';
        i += 2; continue;
      }
      if (i === 0) { out += '\u0627\u0648'; }
      else if (i === len - 1) { out += '\u0648'; }
    }
    else if (c === 'i') {
      if (i === 0) { out += '\u0627\u06CC'; }
      else { out += '\u06CC'; }
    }
    else if (c === 'e') {
      if (i + 1 < len && s[i+1] === 'e') {
        out += (i === 0) ? '\u0627\u06CC' : '\u06CC';
        i += 2; continue;
      }
      if (i === 0) { out += '\u0627'; }
      else if (i === len - 1) { out += '\u0647'; }
    }
    else if (c === 'u') { out += '\u0648'; }
    else if (c === '2') { out += '\u0621'; }
    else if (c === '3') { out += '\u0639'; }
    else if (c === "'" || c === '\u2019') { out += '\u0639'; }
    i++;
  }
  return (out + suffix) || s;
}

// --- MAIN ---
var target = arguments[0];
var keyEvt = arguments[1];
if (!target || typeof target.getTextBeforeCaret !== 'function') {
  return 1;
}

// Determine what character triggered the call (space, period, etc.)
var triggerChar = ' ';
if (keyEvt && keyEvt.Lcode) {
  var code = keyEvt.Lcode;
  if (code === 190) triggerChar = '.';
  else if (code === 188) triggerChar = '\u060C'; // \u060C Persian comma
  else if (code === 191) triggerChar = '\u061F'; // \u061F Persian question mark
  else if (code === 49) triggerChar = '!';
  else if (code === 186) {
    // K_COLON carries the same Lcode shifted and unshifted; check modifiers
    var shifted = !!(keyEvt.Lmodifiers & 0x10);
    triggerChar = shifted ? ':' : '\u061B'; // : or \u061B Persian semicolon
  }
  else if (code === 59) triggerChar = ':';
  else if (code === 13) triggerChar = '\n';
}

var before = target.getTextBeforeCaret();
var m = before.match(/((?:['\u201923])?[a-zA-Z][a-zA-Z'\u201923]*)$/);

// Double-space → period: a quick second space after a completed word
// becomes ". " (iOS convention). Timestamp lives on the global object
// because this file re-executes in a fresh scope on every trigger.
// DISABLED per product decision 2026-07-10 (Mattin prefers plain spaces);
// implementation kept — flip the flag to re-enable.
var DOUBLE_SPACE_PERIOD = false;
var g = (typeof globalThis !== 'undefined') ? globalThis : null;
var nowTs = Date.now();

if (!m) {
  if (triggerChar === ' ' && g && DOUBLE_SPACE_PERIOD) {
    var lastCh = before.charAt(before.length - 1);
    var prevCh = before.charAt(before.length - 2);
    var quick = (nowTs - (g.__fingilishLastSpaceTs || 0)) < 500;
    if (quick && lastCh === ' ' && prevCh &&
        ' .\u060C,!\u061F?:\u061B;\n'.indexOf(prevCh) < 0) {
      target.deleteCharsBeforeCaret(1);
      target.insertTextBeforeCaret('. ');
      g.__fingilishLastSpaceTs = 0;
      return 1;
    }
    g.__fingilishLastSpaceTs = nowTs;
  }
  // No Latin word — just insert the trigger character
  target.insertTextBeforeCaret(triggerChar);
  return 1;
}

var rawWord = m[1];
var wordLen = rawWord.length;
var lowerWord = rawWord.toLowerCase();

// Lookup: 1) exact → 2) bare → 3) normalized → 4) skeleton, shared with the
// -em refinement below; 5) algorithmic fallback.
// hasOwnProperty guards: bare D[w] resolves inherited Object.prototype
// members (typing "constructor" would insert function source!)
var hasOwn = Object.prototype.hasOwnProperty;
function lookupTiers(w) {
  if (hasOwn.call(D, w)) { return D[w]; }
  // Bare tier: apostrophe/Arabizi digits stripped, before norm collapses
  // long vowels (sa'at → saat must hit the exact key, not norm to 'sat')
  var b = w.replace(/['\u201923]/g, '');
  if (b !== w && hasOwn.call(D, b)) { return D[b]; }
  // Explicit 'aa' start = user forcing the long-A letterform. If the
  // exact/bare tiers missed, do NOT let norm() collapse aa->a into a
  // different word; fall through to translit (aa -> ALEF-MADDA).
  if (b.indexOf('aa') === 0) { return null; }
  var n2 = norm(w);
  if (hasOwn.call(D, n2)) { return D[n2]; }
  var s2 = skel(n2);
  if (hasOwn.call(S, s2)) { return S[s2]; }
  return null;
}
var persian = lookupTiers(lowerWord);
// Colloquial we-form: a typed final -em (kardem, raftem, hastem) means the
// -im conjugation when both forms share a stem. skel() strips the 'e' and
// collapses kardem onto کردم; but the user TYPED the disambiguating vowel
// ('e', not 'a'). Prefer the -im variant iff it equals the plain result
// with YEH inserted before the final MEEM (same stem, we-form vs I-form).
// Non-verbs are provably untouched: salem→سالم keeps سالم (سلیم fails the
// stem test), moallem keeps its current mapping.
if (persian && lowerWord.length > 3 && lowerWord.slice(-2) === 'em'
    && persian.slice(-1) === '\u0645') {
  var emVariant = lookupTiers(lowerWord.slice(0, -2) + 'im');
  if (emVariant && emVariant === persian.slice(0, -1) + '\u06CC\u0645') {
    persian = emVariant;
  }
}
if (!persian) { persian = translit(lowerWord); }

target.deleteCharsBeforeCaret(wordLen);
target.insertTextBeforeCaret(persian + triggerChar);
// Arm the double-space window: a quick space right after a space-triggered
// conversion should produce ". " (word + double-tap space).
if (g) { g.__fingilishLastSpaceTs = (triggerChar === ' ') ? nowTs : 0; }

return 1;
'''


def main():
    if not DICT_JSON.exists():
        print(f"ERROR: {DICT_JSON} not found. Run build_dict.py first.")
        return

    import json
    data = json.loads(DICT_JSON.read_text(encoding="utf-8"))
    exact, skel = data["exact"], data["skel"]

    code = (TEMPLATE
            .replace("%%DICT%%", json.dumps(exact, ensure_ascii=False, separators=(',', ':')))
            .replace("%%SKEL%%", json.dumps(skel, ensure_ascii=False, separators=(',', ':')))
            .replace("%%COUNT%%", str(len(exact)))
            .replace("%%SKELCOUNT%%", str(len(skel))))
    count = len(exact)

    OUTPUT.write_text(code, encoding="utf-8")

    print(f"ConvertWord.call_js: {OUTPUT.stat().st_size:,} bytes ({count} dict entries)")
    print(f"Output: {OUTPUT}")


if __name__ == "__main__":
    main()