#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_calljs.py — Assemble ConvertWord.call_js from template + dictionary

Run after build_dict.py:
  python build_dict.py        # generates fingilish_dict.json
  python build_calljs.py      # generates ConvertWord.call_js

Then rebuild with kmc:
  kmc build source/fingilish.kmn --out-file build/fingilish.js
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DICT_JSON = BASE_DIR / "fingilish_dict.json"
OUTPUT = BASE_DIR / "ConvertWord.call_js"

TEMPLATE = r'''// ConvertWord.call_js — Fingilish → Persian conversion engine
// Generated by build_calljs.py — do NOT edit by hand
// API: target.getTextBeforeCaret(), .deleteCharsBeforeCaret(n), .insertTextBeforeCaret(s)

// --- DICTIONARY (%%COUNT%% entries) ---
var D = %%DICT%%;

// --- NORMALIZE: collapse spelling variants to canonical ---
// Must stay in sync with norm() in build_dict.py and searchTermToKey
// in the lexical model.
function norm(s) {
  s = s.toLowerCase();
  // Consonant equivalences
  s = s.replace(/x/g, 'kh');
  s = s.replace(/q/g, 'gh');
  s = s.replace(/w/g, 'v');
  s = s.replace(/ph/g, 'f');
  // Long vowels → short
  s = s.replace(/aa/g, 'a');
  s = s.replace(/oo/g, 'o');
  s = s.replace(/ee/g, 'i');
  s = s.replace(/ou/g, 'o');
  // u/oo equivalence
  s = s.replace(/u/g, 'o');
  // ei/ey → i
  s = s.replace(/ey/g, 'i');
  s = s.replace(/ei/g, 'i');
  // Collapse doubled letters
  s = s.replace(/(.)\1+/g, '$1');
  return s;
}

// --- ALGORITHMIC TRANSLITERATION: for unknown words ---
// Handles any Latin input. Collapses double consonants.
function translit(s) {
  s = s.toLowerCase();
  // Collapse double consonants BEFORE transliterating
  // "mattin" → "matin", "mohammad" → "mohamad"
  s = s.replace(/([^aeiou])\1+/g, '$1');

  var out = '';
  var i = 0;
  var len = s.length;
  // Digraphs (check first, longest match)
  var di = {
    'sh':'\u0634','ch':'\u0686','zh':'\u0698','kh':'\u062E',
    'gh':'\u063A','th':'\u062B','ph':'\u0641'
  };
  // Single consonants
  var co = {
    'b':'\u0628','p':'\u067E','t':'\u062A','s':'\u0633',
    'j':'\u062C','d':'\u062F','z':'\u0632','r':'\u0631',
    'f':'\u0641','k':'\u06A9','g':'\u06AF','l':'\u0644',
    'm':'\u0645','n':'\u0646','v':'\u0648','w':'\u0648',
    'h':'\u0647','y':'\u06CC','q':'\u0642','x':'\u062E'
  };
  // Vowel handling is context-dependent
  while (i < len) {
    // Try digraph first
    if (i + 1 < len) {
      var pair = s[i] + s[i+1];
      if (di[pair]) { out += di[pair]; i += 2; continue; }
    }
    var c = s[i];
    // Consonants
    if (co[c]) {
      out += co[c];
    }
    // Vowels — context-dependent
    else if (c === 'a') {
      // Word-initial 'a' → alef; mid-word 'a' → usually silent
      if (i === 0) { out += '\u0627'; }
      // After another vowel → alef
      else if ('aeiou'.indexOf(s[i-1]) >= 0) { out += '\u0627'; }
      // Otherwise skip (short vowel, not written in Persian)
    }
    else if (c === 'e') {
      // Word-initial 'e' → alef
      if (i === 0) { out += '\u0627'; }
      // Before word end → ه (heh)
      else if (i === len - 1) { out += '\u0647'; }
      // Otherwise skip (short vowel)
    }
    else if (c === 'o') {
      // Word-initial 'o' → alef+vav
      if (i === 0) { out += '\u0627\u0648'; }
      // Between consonants when it's long 'oo' → vav (already collapsed)
      // Otherwise skip (short vowel)
    }
    else if (c === 'i') {
      // Word-initial → alef+ya
      if (i === 0) { out += '\u0627\u06CC'; }
      // Otherwise → ya
      else { out += '\u06CC'; }
    }
    else if (c === 'u') {
      // u → vav
      out += '\u0648';
    }
    // Numbers pass through
    else if (c >= '0' && c <= '9') {
      out += c;
    }
    i++;
  }
  return out || s;
}

// --- MAIN ---
var target = arguments[0];
var keyEvt = arguments[1];
if (!target || typeof target.getTextBeforeCaret !== 'function') {
  return 1;
}

// Determine what character triggered the call (space, period, etc.)
var triggerChar = ' ';
if (keyEvt && keyEvt.Lcode) {
  var code = keyEvt.Lcode;
  if (code === 190) triggerChar = '.';
  else if (code === 188) triggerChar = ',';
  else if (code === 191) triggerChar = '\u061F'; // ؟ Persian question mark
  else if (code === 49) triggerChar = '!';
  else if (code === 186) triggerChar = ';';
  else if (code === 59) triggerChar = ':'; // shift+;
  else if (code === 13) triggerChar = '\n';
}

var before = target.getTextBeforeCaret();
var m = before.match(/([a-zA-Z]+)$/);

if (!m) {
  // No Latin word — just insert the trigger character
  target.insertTextBeforeCaret(triggerChar);
  return 1;
}

var rawWord = m[1];
var wordLen = rawWord.length;
var lowerWord = rawWord.toLowerCase();

// Lookup: 1) exact → 2) normalized → 3) algorithmic fallback
var persian = D[lowerWord];
if (!persian) { persian = D[norm(lowerWord)]; }
if (!persian) { persian = translit(lowerWord); }

target.deleteCharsBeforeCaret(wordLen);
target.insertTextBeforeCaret(persian + triggerChar);

return 1;
'''


def main():
    if not DICT_JSON.exists():
        print(f"ERROR: {DICT_JSON} not found. Run build_dict.py first.")
        return

    dict_data = DICT_JSON.read_text(encoding="utf-8")

    import json
    count = len(json.loads(dict_data))

    code = TEMPLATE.replace("%%DICT%%", dict_data).replace("%%COUNT%%", str(count))

    OUTPUT.write_text(code, encoding="utf-8")

    print(f"ConvertWord.call_js: {OUTPUT.stat().st_size:,} bytes ({count} dict entries)")
    print(f"Output: {OUTPUT}")


if __name__ == "__main__":
    main()