#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_calljs.py — Assemble ConvertWord.call_js from template + dictionary

Run after build_dict.py:
  python build_dict.py        # generates fingilish_dict.json
  python build_calljs.py      # generates ConvertWord.call_js

Then rebuild with kmc:
  kmc build source/fingilish.kmn --out-file build/fingilish.js
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DICT_JSON = BASE_DIR / "fingilish_dict.json"
OUTPUT = BASE_DIR / "ConvertWord.call_js"

TEMPLATE = r'''// ConvertWord.call_js — Fingilish → Persian conversion engine
// Generated by build_calljs.py — do NOT edit by hand
// API: target.getTextBeforeCaret(), .deleteCharsBeforeCaret(n), .insertTextBeforeCaret(s)

// --- DICTIONARY (%%COUNT%% entries) ---
var D = %%DICT%%;
// --- SKELETON BANK (%%SKELCOUNT%% vowel-stripped entries) ---
var S = %%SKEL%%;

// --- NORMALIZE: collapse spelling variants to canonical ---
// Must stay in sync with norm() in build_dict.py and searchTermToKey
// in the lexical model.
function norm(s) {
  s = s.toLowerCase();
  // Strip apostrophes and Arabizi digits (2=\u0621, 3=\u0639) — dict keys are bare
  s = s.replace(/['\u201923]/g, '');
  // c → s before e/i/y (cinema→sinema), else c → k; 'ch' protected
  s = s.replace(/c(?=[eiy])/g, 's');
  s = s.replace(/c(?!h)/g, 'k');
  // Word-final consonant+y → i  (kardy → kardi)
  s = s.replace(/([^aeiou])y$/, '$1i');
  // Word-final 'eh' → 'e'  (kardeh → karde)
  s = s.replace(/eh$/, 'e');
  // Consonant equivalences
  s = s.replace(/x/g, 'kh');
  s = s.replace(/q/g, 'gh');
  s = s.replace(/w/g, 'v');
  s = s.replace(/ph/g, 'f');
  // Long vowels → short
  s = s.replace(/aa/g, 'a');
  s = s.replace(/oo/g, 'o');
  s = s.replace(/ee/g, 'i');
  s = s.replace(/ou/g, 'o');
  // u/oo equivalence
  s = s.replace(/u/g, 'o');
  // ei/ey → i
  s = s.replace(/ey/g, 'i');
  s = s.replace(/ei/g, 'i');
  // y → i everywhere (saye→saie, miyam→miiam→miam)
  s = s.replace(/y/g, 'i');
  // Collapse doubled letters
  s = s.replace(/(.)\1+/g, '$1');
  return s;
}

// --- SKELETON: vowel-stripped key for tier-3 lookup ---
// Must stay in sync with skeleton() in build_dict.py.
function skel(s) {
  if (s.length < 2) { return s; }
  var head = s[0];
  if ('aeou'.indexOf(head) >= 0) { head = 'a'; }
  var body = s.slice(1);
  if (body.length > 1) {
    body = body.slice(0, -1).replace(/[aeo]/g, '') + body.slice(-1);
  }
  return head + body;
}

// --- ALGORITHMIC TRANSLITERATION: for unknown words ---
// Handles any Latin input. Collapses double consonants.
function translit(s) {
  s = s.toLowerCase();
  // c → s before e/i/y, else k ('ch' protected, handled as digraph)
  s = s.replace(/c(?=[eiy])/g, 's');
  s = s.replace(/c(?!h)/g, 'k');
  // Collapse double consonants BEFORE transliterating
  // "mattin" → "matin", "mohammad" → "mohamad"
  s = s.replace(/([^aeiou])\1+/g, '$1');

  var out = '';
  var i = 0;
  var len = s.length;
  // Digraphs (check first, longest match)
  var di = {
    'sh':'\u0634','ch':'\u0686','zh':'\u0698','kh':'\u062E',
    'gh':'\u063A','ph':'\u0641'
  };
  // Single consonants
  var co = {
    'b':'\u0628','p':'\u067E','t':'\u062A','s':'\u0633',
    'j':'\u062C','d':'\u062F','z':'\u0632','r':'\u0631',
    'f':'\u0641','k':'\u06A9','g':'\u06AF','l':'\u0644',
    'm':'\u0645','n':'\u0646','v':'\u0648','w':'\u0648',
    'h':'\u0647','y':'\u06CC','q':'\u0642','x':'\u062E'
  };
  // Vowel handling is context-dependent
  while (i < len) {
    // Try digraph first
    if (i + 1 < len) {
      var pair = s[i] + s[i+1];
      if (di[pair]) { out += di[pair]; i += 2; continue; }
    }
    var c = s[i];
    // Consonants
    if (co[c]) {
      out += co[c];
    }
    // Vowels — context-dependent
    else if (c === 'a') {
      // Word-initial 'aa' → آ (long alef with madda)
      if (i === 0 && i + 1 < len && s[i+1] === 'a') {
        out += '\u0622'; i += 2; continue;
      }
      // 'aa' elsewhere → single alef
      if (i + 1 < len && s[i+1] === 'a') {
        out += '\u0627'; i += 2; continue;
      }
      // Single 'a' → alef, always (user rule: a is alef, not just aa)
      out += '\u0627';
    }
    else if (c === 'o') {
      // 'oo' → vav (long vowel: joon→جون); word-initial 'oo' → او
      if (i + 1 < len && s[i+1] === 'o') {
        out += (i === 0) ? '\u0627\u0648' : '\u0648';
        i += 2; continue;
      }
      // Word-initial 'o' → alef+vav
      if (i === 0) { out += '\u0627\u0648'; }
      // Word-final 'o' is a written vav (boro→\u0628\u0631\u0648, filmo)
      else if (i === len - 1) { out += '\u0648'; }
      // Otherwise skip (short vowel)
    }
    else if (c === 'i') {
      // Word-initial → alef+ya
      if (i === 0) { out += '\u0627\u06CC'; }
      // Otherwise → ya
      else { out += '\u06CC'; }
    }
    else if (c === 'e') {
      // 'ee' → ya (long vowel: azeez→عزیز spelled ازیز)
      if (i + 1 < len && s[i+1] === 'e') {
        out += (i === 0) ? '\u0627\u06CC' : '\u06CC';
        i += 2; continue;
      }
      // fallthrough to existing single-'e' handling below
      if (i === 0) { out += '\u0627'; }
      else if (i === len - 1) { out += '\u0647'; }
      // Otherwise skip (short vowel)
    }
    else if (c === 'u') {
      // u → vav
      out += '\u0648';
    }
    // Arabizi: 2 = hamze, 3 = eyn; apostrophe = eyn
    else if (c === '2') { out += '\u0621'; }
    else if (c === '3') { out += '\u0639'; }
    else if (c === "'" || c === '\u2019') { out += '\u0639'; }
    i++;
  }
  return out || s;
}

// --- MAIN ---
var target = arguments[0];
var keyEvt = arguments[1];
if (!target || typeof target.getTextBeforeCaret !== 'function') {
  return 1;
}

// Determine what character triggered the call (space, period, etc.)
var triggerChar = ' ';
if (keyEvt && keyEvt.Lcode) {
  var code = keyEvt.Lcode;
  if (code === 190) triggerChar = '.';
  else if (code === 188) triggerChar = '\u060C'; // \u060C Persian comma
  else if (code === 191) triggerChar = '\u061F'; // \u061F Persian question mark
  else if (code === 49) triggerChar = '!';
  else if (code === 186) {
    // K_COLON carries the same Lcode shifted and unshifted; check modifiers
    var shifted = !!(keyEvt.Lmodifiers & 0x10);
    triggerChar = shifted ? ':' : '\u061B'; // : or \u061B Persian semicolon
  }
  else if (code === 59) triggerChar = ':';
  else if (code === 13) triggerChar = '\n';
}

var before = target.getTextBeforeCaret();
var m = before.match(/([a-zA-Z][a-zA-Z'\u201923]*)$/);

if (!m) {
  // No Latin word — just insert the trigger character
  target.insertTextBeforeCaret(triggerChar);
  return 1;
}

var rawWord = m[1];
var wordLen = rawWord.length;
var lowerWord = rawWord.toLowerCase();

// Lookup: 1) exact → 2) normalized → 3) skeleton → 4) algorithmic fallback
// hasOwnProperty guards: bare D[w] resolves inherited Object.prototype
// members (typing "constructor" would insert function source!)
var hasOwn = Object.prototype.hasOwnProperty;
var persian = hasOwn.call(D, lowerWord) ? D[lowerWord] : null;
// Bare tier: apostrophe/Arabizi digits stripped, before norm collapses
// long vowels (sa'at → saat must hit the exact key, not norm to 'sat')
var bare = lowerWord.replace(/['\u201923]/g, '');
if (!persian && bare !== lowerWord && hasOwn.call(D, bare)) { persian = D[bare]; }
var nw = norm(lowerWord);
if (!persian && hasOwn.call(D, nw)) { persian = D[nw]; }
if (!persian) {
  var sk = skel(nw);
  if (hasOwn.call(S, sk)) { persian = S[sk]; }
}
if (!persian) { persian = translit(lowerWord); }

target.deleteCharsBeforeCaret(wordLen);
target.insertTextBeforeCaret(persian + triggerChar);

return 1;
'''


def main():
    if not DICT_JSON.exists():
        print(f"ERROR: {DICT_JSON} not found. Run build_dict.py first.")
        return

    import json
    data = json.loads(DICT_JSON.read_text(encoding="utf-8"))
    exact, skel = data["exact"], data["skel"]

    code = (TEMPLATE
            .replace("%%DICT%%", json.dumps(exact, ensure_ascii=False, separators=(',', ':')))
            .replace("%%SKEL%%", json.dumps(skel, ensure_ascii=False, separators=(',', ':')))
            .replace("%%COUNT%%", str(len(exact)))
            .replace("%%SKELCOUNT%%", str(len(skel))))
    count = len(exact)

    OUTPUT.write_text(code, encoding="utf-8")

    print(f"ConvertWord.call_js: {OUTPUT.stat().st_size:,} bytes ({count} dict entries)")
    print(f"Output: {OUTPUT}")


if __name__ == "__main__":
    main()