#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_model_key.py — single-source the lexical model's searchTermToKey.

Generates a self-contained JS implementation of:
    key(term) = skel(norm( isPersian(term) ? p2l(term) : term ))
where p2l is a JS port of build_dict.transliterate_for_dict with tables
EMITTED FROM build_dict's own dicts, and norm/skel are JS ports of
build_dict.norm/skeleton. Both the banner's Persian-index path and the
typed-query path therefore produce keys in the SAME (converter tier-3)
skeleton space — ending the two-dialect searchTermToKey (doc-04 L4).

Steps:
  1. Emit the JS fragment.
  2. DIFFERENTIAL PROOF: run python vs node over every wordlist word,
     every names.tsv Persian, and every dict latin key. Any mismatch
     aborts (non-zero exit; build.sh gates on it).
  3. Inject the new searchTermToKey into mattin.fa.fingilish.model.ts.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

import build_dict as bd

BASE = Path(__file__).resolve().parent
MODEL = BASE.parent / "mattin.fa.fingilish.model.ts"

# ---------------------------------------------------------------- fragment
def js_fragment():
    multi = json.dumps(bd.TRANSLIT_MULTI, ensure_ascii=True, sort_keys=True)
    single = json.dumps(bd.TRANSLIT_SINGLE, ensure_ascii=True, sort_keys=True)
    cons = json.dumps("".join(sorted(bd.CONSONANTS)), ensure_ascii=True)
    return r'''
    // ==== GENERATED BY gen_model_key.py — DO NOT EDIT BY HAND ====
    // Tables come from build_dict.py (single source of truth).
    var P2L_MULTI: Record<string, string> = ''' + multi + r''';
    var P2L_SINGLE: Record<string, string> = ''' + single + r''';
    var P2L_CONS: string = ''' + cons + r''';

    function p2l(word: string): string {
      if (!word) { return "?"; }
      var n = word.length;
      var result = "";
      var i = 0;
      while (i < n) {
        var ch = word[i];
        if (i + 1 < n) {
          var pair = word[i] + word[i + 1];
          if (P2L_MULTI.hasOwnProperty(pair)) {
            result += P2L_MULTI[pair];
            i += 2;
            continue;
          }
        }
        if (ch === '\u0648') {
          var prevC = (i > 0 && P2L_CONS.indexOf(word[i - 1]) >= 0);
          var nextC = (i + 1 < n && P2L_CONS.indexOf(word[i + 1]) >= 0);
          var nextEnd = (i + 1 >= n);
          if (i === 0) { result += "va"; }
          else if (i === 1 && word[0] === '\u0627') { result += "oo"; }
          else if (prevC && (nextC || nextEnd)) { result += "oo"; }
          else { result += "v"; }
          i += 1;
          continue;
        }
        if (ch === '\u0647' && i === n - 1) { result += "e"; i += 1; continue; }
        if (ch === '\u0639' && i === 0) { result += "a"; i += 1; continue; }
        if (P2L_SINGLE.hasOwnProperty(ch)) { result += P2L_SINGLE[ch]; }
        i += 1;
      }
      result = result.replace(/(.)\1{2,}/g, '$1$1');
      result = result.replace(/^\s+|\s+$/g, '');
      return result || "?";
    }

    function normL(s: string): string {
      s = s.toLowerCase();
      s = s.replace(/['\u201923]/g, '');
      s = s.replace(/c(?=[eiy])/g, 's');
      s = s.replace(/c(?!h)/g, 'k');
      s = s.replace(/([^aeiou])y$/, '$1i');
      s = s.replace(/eh$/, 'e');
      s = s.replace(/x/g, 'kh');
      s = s.replace(/q/g, 'gh');
      s = s.replace(/w/g, 'v');
      s = s.replace(/ph/g, 'f');
      s = s.replace(/aa/g, 'a');
      s = s.replace(/oo/g, 'o');
      s = s.replace(/ee/g, 'i');
      s = s.replace(/ou/g, 'o');
      s = s.replace(/u/g, 'o');
      s = s.replace(/ey/g, 'i');
      s = s.replace(/ei/g, 'i');
      s = s.replace(/y/g, 'i');
      s = s.replace(/(.)\1+/g, '$1');
      return s;
    }

    function skelL(s: string): string {
      if (s.length < 2) { return s; }
      var head = s[0];
      if ('aeou'.indexOf(head) >= 0) { head = 'a'; }
      var body = s.slice(1);
      if (body.length > 1) {
        body = body.slice(0, -1).replace(/[aeo]/g, '') + body.slice(-1);
      }
      return head + body;
    }
    // ==== END GENERATED ====
'''

FRAGMENT = js_fragment()

NEW_FN = (
    "searchTermToKey: function(term: string): string {\n"
    "    // Strip BiDi isolates (wordlist wraps Persian in RLI/PDI)\n"
    "    term = term.replace(/[\\u2066-\\u2069]/g, '').replace(/^\\s+|\\s+$/g, '');\n"
    + FRAGMENT +
    "    if (/[\\u0600-\\u06FF]/.test(term)) { term = p2l(term); }\n"
    "    return skelL(normL(term));\n"
    "  }"
)

# ---------------------------------------------------------------- diff test
def differential_proof():
    words = set()
    wl = BASE / "fingilish.wordlist.tsv"
    for line in wl.open(encoding="utf-8"):
        w = re.sub(r"[\u2066-\u2069]", "", line.split("\t")[0]).strip()
        if w:
            words.add(w)
    names = BASE / "names.tsv"
    if names.exists():
        for line in names.open(encoding="utf-8"):
            words.add(line.split("\t")[0].strip())
    latins = set()
    dict_json = json.load((BASE / "fingilish_dict.json").open(encoding="utf-8"))
    latins.update(dict_json["exact"].keys())

    def py_key(t):
        t = re.sub(r"[\u2066-\u2069]", "", t).strip()
        if re.search(r"[\u0600-\u06FF]", t):
            t = bd.transliterate_for_dict(t)
        return bd.skeleton(bd.norm(t))

    cases = sorted(words) + sorted(latins)
    expected = [py_key(c) for c in cases]

    # node side: extract fragment as plain JS (strip TS annotations)
    js = FRAGMENT
    js = re.sub(r": Record<string, string>", "", js)
    js = re.sub(r": string\b", "", js)
    harness = (
        js
        + "\nconst cases = JSON.parse(require('fs').readFileSync('/tmp/fng_diff_cases.json','utf8'));\n"
        + "const out = cases.map(t => {\n"
        + "  t = t.replace(/[\\u2066-\\u2069]/g, '').replace(/^\\s+|\\s+$/g, '');\n"
        + "  if (/[\\u0600-\\u06FF]/.test(t)) { t = p2l(t); }\n"
        + "  return skelL(normL(t));\n"
        + "});\n"
        + "require('fs').writeFileSync('/tmp/fng_diff_out.json', JSON.stringify(out));\n"
    )
    Path("/tmp/fng_diff_cases.json").write_text(json.dumps(cases, ensure_ascii=True), encoding="utf-8")
    Path("/tmp/fng_diff.js").write_text(harness, encoding="utf-8")
    subprocess.run(["node", "/tmp/fng_diff.js"], check=True)
    got = json.loads(Path("/tmp/fng_diff_out.json").read_text(encoding="utf-8"))
    bad = [(c, e, g) for c, e, g in zip(cases, expected, got) if e != g]
    print(f"  differential proof: {len(cases):,} cases, {len(bad)} mismatches")
    if bad:
        for c, e, g in bad[:10]:
            print("   MISMATCH", c.encode("unicode_escape").decode(), "py:", e, "js:", g)
        sys.exit(1)

# ---------------------------------------------------------------- inject
def inject():
    src = MODEL.read_text(encoding="utf-8")
    m = re.search(r"searchTermToKey: function\(term: string\): string \{.*?\n  \}", src, re.S)
    if not m:
        print("searchTermToKey not found in model.ts")
        sys.exit(1)
    src = src[: m.start()] + NEW_FN + src[m.end():]
    MODEL.write_text(src, encoding="utf-8")
    print(f"  model.ts searchTermToKey regenerated ({len(NEW_FN):,} chars)")

if __name__ == "__main__":
    differential_proof()
    inject()
