#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
model_emit.py — emit the custom-1.0 model's generated sources from the
CONVERTER's own build products (true single source, doc-04 L3/L4/L6):

  fng_model_fns.js  : norm/skel/translit extracted VERBATIM from the
                      generated ConvertWord.call_js (same bytes the
                      converter runs)
  fng_model_data.js : FNG_DICT (exact+skel from fingilish_dict.json) +
                      FNG_ALTS (fng_model_alts.json)

Runs AFTER build_dict.py + build_calljs.py. Gated downstream by the
compiled-model harness (test_custom_model.mjs).
"""
import json
from pathlib import Path

BASE = Path(__file__).resolve().parent
OUT_FNS = BASE.parent / "fng_model_fns.js"
OUT_DATA = BASE.parent / "fng_model_data.js"

calljs = (BASE / "ConvertWord.call_js").read_text(encoding="utf-8")
start = calljs.index("// --- NORMALIZE")
end = calljs.index("// --- MAIN ---")
fns = calljs[start:end]
for required in ("function norm(", "function skel(", "function translit("):
    assert required in fns, required

OUT_FNS.write_text(
    "// GENERATED by model_emit.py from ConvertWord.call_js - DO NOT EDIT\n"
    "// (verbatim converter functions: norm / skel / translit)\n" + fns,
    encoding="utf-8")

dict_data = json.loads((BASE / "fingilish_dict.json").read_text(encoding="utf-8"))
alts = json.loads((BASE / "fng_model_alts.json").read_text(encoding="utf-8"))
OUT_DATA.write_text(
    "// GENERATED by model_emit.py - DO NOT EDIT\n"
    "var FNG_DICT = " + json.dumps(dict_data, ensure_ascii=False) + ";\n"
    "var FNG_ALTS = " + json.dumps(alts, ensure_ascii=False) + ";\n",
    encoding="utf-8")

print(f"  fng_model_fns.js: {OUT_FNS.stat().st_size:,} B; "
      f"fng_model_data.js: {OUT_DATA.stat().st_size:,} B")
